[package]
name = "ksip"
version = "0.0.5"
edition = "2021"
description = "KSIP Windows SIP client"
license = "MIT"
authors = ["Kashihara City"]
repository = "https://github.com/kashihara-city/ksip"

[[bin]]
name = "ksip"
path = "src/main.rs"

[features]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
serde = { version = "1", features = ["derive"] }
tauri-plugin-global-shortcut = "2"
tauri-plugin-notification = "2"
serde_json = "1"
winreg = "=0.55.0"
windows-sys = { version = "=0.61.2", features = ["Win32_Foundation", "Win32_Globalization", "Win32_NetworkManagement_IpHelper", "Win32_NetworkManagement_Ndis", "Win32_Networking_WinSock", "Win32_Security_Credentials", "Win32_Security_Cryptography", "Win32_Storage_FileSystem", "Win32_System_DataExchange", "Win32_System_IO", "Win32_System_Pipes", "Win32_System_Memory", "Win32_System_SystemInformation", "Win32_System_Time", "Win32_System_Threading", "Win32_UI_Controls_Dialogs", "Win32_UI_Shell"] }

windows = { version = "=0.61.3", features = ["Win32_Media_Audio", "Win32_Media_Audio_Endpoints", "Win32_Media_KernelStreaming", "Win32_Media_Multimedia", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Variant", "Win32_UI_Shell_PropertiesSystem", "Win32_Devices_FunctionDiscovery"] }
miniz_oxide = "=0.9.1"

[profile.release]
opt-level = "z"
strip = true
lto = "fat"
codegen-units = 1
